### PR TITLE
Add translation for Norwegian Bokmål

### PR DESCRIPTION
**Pull request by hgrimelid**
This PR contains translation for Norwegian Bokmål.

### CODE REVIEW

**Comment by martyf** [comment]
Thanks for your contribution, @hgrimelid 🎉

**Comment by martyf** [comment]
I'm working on an opt-in feature when two factor is not enforced for a user, and would love your help with a few translations. One of the steps has improved language between the logged in user (self) and another user.

These are in the `resources/lang/en/profile.php` file.

These are the strings that have changed: I'd love it if you could reply to this with correct translations to Norwegian Bokmål for these strings.

I can then take it from there and merge in to the `feature/opt-in` branch.

If I don't hear from you I will try my best with Google Translate but isn't always the best.

```php
    'reset' => [
        'me_intro_1' => 'This will remove all two factor authentication details from your account.',
        'me_intro_2' => 'You can set up two factor authentication again from your Profile in the Control Panel.',

        'me_enforced_intro_1' => 'This will remove all two factor authentication details from your account, and log you out.',
        'me_enforced_intro_2' => 'The next time you log in, you will need to set up two factor authentication again before you can access the Control Panel.',

        'user_intro_1' => 'This will remove all two factor authentication details from their account.',
        'user_intro_2' => 'They will be able to enable two factor authentication from their Profile in the Control Panel.',

        'user_enforced_intro_1' => 'This will remove all two factor authentication details from their account, and log you them out.',
        'user_enforced_intro_2' => 'The next time they log in, they will need to set up two factor authentication again before they can access the Control Panel.',

        'confirm' => [
            'me_1' => 'This will remove all two factor authentication details from your account.',
            'me_2' => 'You can set up two factor authentication from your Profile in the Control Panel.',
            'me_3' => 'Are you really sure you want to do this?',

            'me_enforced_1' => 'This will remove all two factor authentication details from your account, and log you out <strong>immediately</strong>.',
            'me_enforced_2' => 'You will need to set up two factor authentication on your next log in.',
            'me_enforced_3' => 'Are you really sure you want to do this?',

            'user_1' => 'This will remove all two factor authentication details from their account.',
            'user_2' => 'They can set up two factor authentication from their Profile in the Control Panel.',
            'user_3' => 'Are you really sure you want to do this?',

            'user_enforced_1' => 'This will remove all two factor authentication details from their account, and log them out on their next visit.',
            'user_enforced_2' => 'They will need to set up two factor authentication on their next log in.',
            'user_enforced_3' => 'Are you really sure you want to do this?',
        ],
    ],
```

**Comment by martyf** [comment]
Just for context too:
- `me` is for when I am the user seeing my own message, and two factor is optional
- `me_enforced` is for when I am the user seeing my own message, and two factor is enforced
- `user` is for when I am looking at another user, and two factor is optional
- `user_enforced` is for when I am looking at another user, and two factor is enforced

**Comment by hgrimelid** [comment]
Here you go @martyf 

```php
    'reset' => [
        'me_intro_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljer fra kontoen din.',
        'me_intro_2' => 'Du kan sette opp tofaktorautentisering igjen fra profilen din i kontrollpanelet.',

        'me_enforced_intro_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljer fra kontoen din og logge deg ut.',
        'me_enforced_intro_2' => 'Neste gang du logger på, må du sette opp tofaktorautentisering igjen før du får tilgang til kontrollpanelet.',

        'user_intro_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljer fra kontoen deres.',
        'user_intro_2' => 'De vil kunne aktivere tofaktorautentisering fra sin profil i kontrollpanelet.',

        'user_enforced_intro_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljene fra kontoen deres, og logge deg ut.',
        'user_enforced_intro_2' => 'Neste gang de logger på, må de sette opp tofaktorautentisering igjen før de får tilgang til kontrollpanelet.',

        'confirm' => [
            'me_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljer fra kontoen din.',
            'me_2' => 'Du kan sette opp tofaktorautentisering fra profilen din i kontrollpanelet.',
            'me_3' => 'Er du sikker på at du vil gjøre dette?',

            'me_enforced_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljene fra kontoen din og logge deg av <strong>umiddelbart</strong>.',
            'me_enforced_2' => 'Du må sette opp tofaktorautentisering ved neste pålogging.',
            'me_enforced_3' => 'Er du sikker på at du vil gjøre dette?',

            'user_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljer fra kontoen deres.',
            'user_2' => 'De kan sette opp tofaktorautentisering fra sin profilside i kontrollpanelet.',
            'user_3' => 'Er du sikker på at du vil gjøre dette?',

            'user_enforced_1' => 'Dette vil fjerne alle tofaktorautentiseringsdetaljene fra kontoen deres, og logge dem ut ved neste besøk.',
            'user_enforced_2' => 'De må sette opp tofaktorautentisering ved neste pålogging.',
            'user_enforced_3' => 'Er du sikker på at du vil gjøre dette?',
        ],
    ],
```

**Comment by martyf** [comment]
Superb - I'll run it through Translate to give it a quick check it makes sense (as far as Google thinks) and let you know when it is tagged.

**Pull request merged**
