### PR TITLE
Added Dutch (The Netherlands) translations

### PR DESCRIPTION
**Pull request by joshuavanderpoll**
Great package 😄, I have made some Dutch translations

### CODE REVIEW

**Comment by martyf** [comment]
🎉 woo, thank you very much for this!

**Comment by martyf** [comment]
I'm working on an opt-in feature when two factor is not enforced for a user, and would love your help with a few translations. One of the steps has improved language between the logged in user (self) and another user.

These are in the `resources/lang/en/profile.php` file.

These are the strings that have changed: I'd love it if you could reply to this with correct Dutch translations for these strings.

I can then take it from there and merge in to the `feature/opt-in` branch.

If I don't hear from you I will try my best with Google Translate but isn't always the best.

```php
    'reset' => [
        'me_intro_1' => 'This will remove all two factor authentication details from your account.',
        'me_intro_2' => 'You can set up two factor authentication again from your Profile in the Control Panel.',

        'me_enforced_intro_1' => 'This will remove all two factor authentication details from your account, and log you out.',
        'me_enforced_intro_2' => 'The next time you log in, you will need to set up two factor authentication again before you can access the Control Panel.',

        'user_intro_1' => 'This will remove all two factor authentication details from their account.',
        'user_intro_2' => 'They will be able to enable two factor authentication from their Profile in the Control Panel.',

        'user_enforced_intro_1' => 'This will remove all two factor authentication details from their account, and log you them out.',
        'user_enforced_intro_2' => 'The next time they log in, they will need to set up two factor authentication again before they can access the Control Panel.',

        'confirm' => [
            'me_1' => 'This will remove all two factor authentication details from your account.',
            'me_2' => 'You can set up two factor authentication from your Profile in the Control Panel.',
            'me_3' => 'Are you really sure you want to do this?',

            'me_enforced_1' => 'This will remove all two factor authentication details from your account, and log you out <strong>immediately</strong>.',
            'me_enforced_2' => 'You will need to set up two factor authentication on your next log in.',
            'me_enforced_3' => 'Are you really sure you want to do this?',

            'user_1' => 'This will remove all two factor authentication details from their account.',
            'user_2' => 'They can set up two factor authentication from their Profile in the Control Panel.',
            'user_3' => 'Are you really sure you want to do this?',

            'user_enforced_1' => 'This will remove all two factor authentication details from their account, and log them out on their next visit.',
            'user_enforced_2' => 'They will need to set up two factor authentication on their next log in.',
            'user_enforced_3' => 'Are you really sure you want to do this?',
        ],
    ],
```

**Comment by martyf** [comment]
Just for context too:
- `me` is for when I am the user seeing my own message, and two factor is optional
- `me_enforced` is for when I am the user seeing my own message, and two factor is enforced
- `user` is for when I am looking at another user, and two factor is optional
- `user_enforced` is for when I am looking at another user, and two factor is enforced

**Comment by joshuavanderpoll** [comment]
Hi, just saw your message and I see you already made the translations. I can confirm they are correct tho.

**Comment by martyf** [comment]
The original translations you provided are only half of them: there are some subtle changes in the new ones. 

Can I get you to please review them? In the original PR there were two variations… but now there are four.

**Comment by martyf** [comment]
I've actually been able to re-use some... but these are the ones that I'd love some input with:

```php
return [

    // "me" is when I am looking at my own profile
    // "user" is when I am looking at another user's profile

    // Shown on the "Profile" screen for a user, before a button that says "Reset two factor setup"

    'me_intro_1' => 'This will remove all two factor authentication details from your account.',
    'me_intro_2' => 'You can set up two factor authentication again from your Profile in the Control Panel.',

    'user_intro_1' => 'This will remove all two factor authentication details from their account.',
    'user_intro_2' => 'They will be able to enable two factor authentication from their Profile in the Control Panel.',

    'confirm' => [
        // Shown in a modal when you attempt to reset/remove two factor from an account

        'me_1' => 'This will remove all two factor authentication details from your account.',
        'me_2' => 'You can set up two factor authentication from your Profile in the Control Panel.',

        'user_1' => 'This will remove all two factor authentication details from their account.',
        'user_2' => 'They can set up two factor authentication from their Profile in the Control Panel.',
    ],    

];
```

**Comment by martyf** [comment]
Thank you! You're an absolute legend!

**Pull request merged**
